# Generated by Django 4.2.7 on 2024-02-01 13:55

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=128, verbose_name='Испонитель')),
                ('name', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('year', models.IntegerField(default=1960, verbose_name='Издан')),
                ('maker', models.CharField(max_length=40, verbose_name='Издатель')),
                ('cover', models.ImageField(storage=albums.models.RewriteStorage(), upload_to=albums.models.upload_cover, verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['artist', 'year'],
            },
        ),
    ]
