# Generated by Django 4.2.7 on 2024-02-14 08:46

import albums.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=128, verbose_name='Испонитель')),
                ('name', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('year', models.PositiveSmallIntegerField(default=1960, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)], verbose_name='Издан')),
                ('maker', models.CharField(max_length=40, verbose_name='Издатель')),
                ('cover', models.ImageField(storage=albums.models.RewriteStorage(), upload_to=albums.models.upload_cover, verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['artist', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_no', models.IntegerField(default=1, verbose_name='Track')),
                ('track_name', models.CharField(max_length=128, verbose_name='Song')),
                ('track_artist', models.CharField(max_length=128, verbose_name='Artist')),
                ('track_time', models.TimeField(default='00:00:00', verbose_name='Length')),
                ('album_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Songs', to='albums.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Композиции',
                'verbose_name_plural': 'Композиции',
                'ordering': ['track_no'],
            },
        ),
    ]
