# Generated by Django 4.2.7 on 2024-02-14 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Length'),
        ),
    ]
