# Generated by Django 4.2.7 on 2024-02-05 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.PositiveSmallIntegerField(default=1960, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)], verbose_name='Издан'),
        ),
    ]
